meta_product_name: "BenchMark"
meta_title: "BenchMark - Invest with your social circle."
meta_description: "BenchMark is a coordination tool for crypto-investors, which helps everyone to stay on the same page."
meta_image: "benchmark-official.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
